os: Visual Studio 2015

environment:
    Toolset: v110

configuration:
    - Debug

platform:
    - Win32

before_build:
- ps: |
    md _build
    cd _build

build_script:
- ps: |
    cmake ..
    & cmake --build .
    & dir /s tests.exe
